## Multiple Variable Linear Regression

In [23]:
import numpy as np
import copy, math
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyles')
np.set_printoptions(precision=2) #reduce display precision on numpy array

## Problem Statement

In [24]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

## Matrix X containing our examples

In [25]:
print(f"X.shape : {X_train.shape}, X dtype {type(X_train)}")
print(X_train)
print(f"y.shape : {y_train.shape}, y dtype{type(y_train)}")
print(y_train)

X.shape : (3, 4), X dtype <class 'numpy.ndarray'>
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y.shape : (3,), y dtype<class 'numpy.ndarray'>
[460 232 178]


## Parameter vector w, b

In [26]:
b_init = 785.1811367994083
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w.shape = {w_init.shape}, b type = {type(b_init)}")

w.shape = (4,), b type = <class 'float'>


## Single Prediction element by element

In [27]:
def prediction_single_loop(x, w, b):
    n = x.shape[0]
    p = 0
    for i in range (n):
        p_i = x[i] * w[i]
        p = p_i + p
    p = p + b
    return p

In [28]:
x_vec = X_train[0, :]
print(f"x_vec shape = {x_vec.shape}, x_vec value = {x_vec}")

f_wb = prediction_single_loop(x_vec, w_init, b_init)
print(f"f_wb shape = {f_wb.shape}, prediction = {f_wb}")

x_vec shape = (4,), x_vec value = [2104    5    1   45]
f_wb shape = (), prediction = 459.9999976194083


## Single Prediction, vector

In [29]:
def pridict (x, w, b):
    p = np.dot(x, w) + b
    return p

In [30]:
x_vec = X_train[0, :]
print(f"x_vec shape = {x_vec.shape}, x_vec value = {x_vec}")

f_wb = pridict(x_vec, w_init, b_init )
print(F"f_wb shape = {f_wb.shape}, pridiction = {f_wb}")

x_vec shape = (4,), x_vec value = [2104    5    1   45]
f_wb shape = (), pridiction = 459.99999761940825


## Compute Cost With Multiple Variables

In [ ]:
def compute_cost (X, y, w, b):
    m = X.shape[0]
    cost = 0.0

    for i in range (m):
        f_wb_i = np.dot(X[i], w) + b
        cost = cost + (f_wb_i - y[i]) ** 2
    cost = cost / (2 * m)
    return cost

In [32]:
cost = compute_cost(X_train, y_train, w_init, b_init)
print(f"cost of optimal w = {cost}")

cost of optimal w = 1.5578904880036537e-12


## Compute Gradient with Multiple Variables

In [33]:
def compute_gradient(X, y, w, b):

    m, n = X.shape
    dj_dw = np.zeros((n,))
    dj_db = 0.

    for i in range (m):
        err = (np.dot(X[i], w) + b) - y[i]
        for j in range (n):
            dj_dw[j] = dj_dw[j] + err * X[i, j]
        dj_db = dj_db + err
    dj_dw = dj_dw / m
    dj_db = dj_db / m

    return dj_db, dj_dw

In [34]:
tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init, b_init)
print(f"dj_db at initial w, b = {tmp_dj_db}")
print(f"dj_dw at intial w,b = \n {tmp_dj_dw}")

dj_db at initial w, b = -1.673925169143331e-06
dj_dw at intial w,b = 
 [-2.73e-03 -6.27e-06 -2.22e-06 -6.92e-05]


## Gradient Descent With Multiple Variables

In [35]:
def gradient_descent(X, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters):
    J_history = []
    w = copy.deepcopy(w_in)
    b = b_in

    for i in range (num_iters):
        dj_db, dj_dw = gradient_function(X, y, w, b)
        w = w - alpha * dj_dw
        b = w - alpha * dj_db
        if i < 100000:
            J_history.append(cost_function(X, y, w, b))
        if i % math.ceil(num_iters / 10) == 0:
            print(f"iteration {i:4d} : cost {J_history[-1]:8.2f}")
    return w, b, J_history

In [37]:
initial_w = np.zeros_like(w_init)
initial_b = 0.

iterations = 1000
alpha = 5.0e-7

w_final, b_final, J_hist = gradient_descent(X_train, y_train, initial_w, initial_b, compute_cost, compute_gradient, alpha , iterations )
print(f"b, w found gradient descent : {b_final:0.2f}, {w_final}")

m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

TypeError: unsupported format string passed to numpy.ndarray.__format__